spring.application.name=veterinaria

# 1. Configuración del puerto dinámico
server.port=${SERVER_PORT:8080}

# 2. Conexión a la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/veterinaria_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

# 3. Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
